server:
  port: 8082
api:
  version: api V2.2

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    metadataMap:
      zone: zone1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # default address

management:
  security:
    enabled: false
