server:
  port: 8083
api:
  name: api2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
